version: 2
updates:
  # Keep Terraform modules up-to-date
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
