AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an encrypted S3 bucket with versioning and an IAM user with AdministratorAccess for Terraform'

Resources:
  EncryptedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-bucket'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  TerraformUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${AWS::StackName}-user'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref EncryptedS3Bucket
  BucketARN:
    Description: ARN of the created S3 bucket
    Value: !GetAtt EncryptedS3Bucket.Arn
  TerraformUserName:
    Description: Name of the created IAM user for Terraform
    Value: !Ref TerraformUser
  TerraformUserARN:
    Description: ARN of the created IAM user for Terraform
    Value: !GetAtt TerraformUser.Arn